/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agentic RAG 对话（Mock 流式） */
        post: operations["ask_api_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ask_graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 医疗疾病问答（Mock 流式） */
        post: operations["ask_graph_api_ask_graph_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 会话列表 */
        get: operations["list_conversations_api_conversations_get"];
        put?: never;
        /** 新建会话 */
        post: operations["create_conversation_api_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除会话（级联删消息） */
        delete: operations["delete_conversation_api_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        /** 重命名会话 */
        patch: operations["rename_conversation_api_conversations__conversation_id__patch"];
        trace?: never;
    };
    "/api/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 拉取历史消息 */
        get: operations["list_messages_api_conversations__conversation_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 依赖健康检查 */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentType
         * @enum {string}
         */
        AgentType: "rag" | "graph";
        /**
         * AskRequest
         * @description 问答请求。前端两个 Tab 共用此结构。
         * @example {
         *       "question": "百日咳有哪些症状",
         *       "use_memory": true
         *     }
         */
        AskRequest: {
            /**
             * Question
             * @description 用户问题
             */
            question: string;
            /**
             * Conversation Id
             * @description 会话 ID，传 null 表示新建
             */
            conversation_id?: string | null;
            /**
             * Use Memory
             * @description 是否携带历史上下文
             * @default true
             */
            use_memory: boolean;
        };
        /**
         * Conversation
         * @description 会话。由 SQLAlchemy ORM 对象直接构造。
         */
        Conversation: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            agent_type: components["schemas"]["AgentType"];
            /** Message Count */
            message_count: number;
            /** Total Tokens */
            total_tokens: number;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** ConversationCreate */
        ConversationCreate: {
            /**
             * Title
             * @default 新会话
             */
            title: string;
            /** @default rag */
            agent_type: components["schemas"]["AgentType"];
        };
        /** ConversationUpdate */
        ConversationUpdate: {
            /** Title */
            title: string;
        };
        /**
         * ErrorBody
         * @description 统一错误信封。`detail` 必须携带真实异常类型与原文（见 接口文档.md §1.3）。
         */
        ErrorBody: {
            /** Code */
            code: number;
            /** Msg */
            msg: string;
            /** Detail */
            detail?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthStatus
         * @description 健康检查。**始终返回 200**，靠字段值判断哪个依赖挂了。
         */
        HealthStatus: {
            /** Mysql */
            mysql: string;
            /** Neo4J */
            neo4j: string;
            /** Ollama */
            ollama: string;
            /** Faiss Index */
            faiss_index: string;
            /** Bm25 Corpus */
            bm25_corpus: string;
            /** Rerank */
            rerank: string;
        };
        /**
         * Message
         * @description 消息。user 角色的 sources 与 token 字段均为 null。
         */
        Message: {
            /** Id */
            id: number;
            role: components["schemas"]["MessageRole"];
            /** Content */
            content: string;
            /** Sources */
            sources?: components["schemas"]["Source"][] | null;
            /** Prompt Tokens */
            prompt_tokens?: number | null;
            /** Completion Tokens */
            completion_tokens?: number | null;
            /** Total Tokens */
            total_tokens?: number | null;
            /** Model */
            model?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Created At */
            created_at: string;
        };
        /**
         * MessageRole
         * @enum {string}
         */
        MessageRole: "user" | "assistant";
        /** Page[Conversation] */
        Page_Conversation_: {
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Items */
            items: components["schemas"]["Conversation"][];
        };
        /** Page[Message] */
        Page_Message_: {
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Items */
            items: components["schemas"]["Message"][];
        };
        /**
         * Source
         * @description 回答的溯源来源。对应 系统设计.md §1.6 与 接口文档.md §3.4.5。
         */
        Source: {
            /**
             * Type
             * @enum {string}
             */
            type: "vector" | "graph";
            /** Name */
            name: string;
            /**
             * Score
             * @description 图谱类固定为 null
             */
            score?: number | null;
            /** Snippet */
            snippet: string;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * StreamEvent
         * @description 流式响应中**一行** NDJSON 的载荷（见 接口文档.md §3.4.2）。
         *
         *     OpenAPI 描述不了「一行一个 JSON、连接关闭即结束」这种协议，所以这个模型
         *     并不是真正的 response_model —— 它的作用是当**类型锚点**：
         *     把它挂到 /api/ask 的 responses 里，`Usage` 与 `Source` 才会被写进
         *     components.schemas，前端 `npm run api:types` 生成出来的类型里才有它们。
         *
         *     接口文档 §6.3 的手写 `StreamEvent` 联合类型（`{sid} | {c} | {s} | {u} | {err}`）
         *     仍然需要手写 —— 联合类型的判别信息在这份 schema 里表达不出来。
         *     但至少 Source / Usage 这两个**嵌套结构**不必再手抄一遍，字段改了也不会漏。
         */
        StreamEvent: {
            /**
             * Sid
             * @description 新建会话时首行下发真实会话 ID
             */
            sid?: string | null;
            /**
             * C
             * @description 正文增量
             */
            c?: string | null;
            /**
             * S
             * @description 溯源来源
             */
            s?: components["schemas"]["Source"][] | null;
            /** @description token 用量 */
            u?: components["schemas"]["Usage"] | null;
            /**
             * Err
             * @description 错误描述，收到后流终止
             */
            err?: string | null;
        };
        /**
         * Usage
         * @description token 用量。本地 Ollama 模型可能不产生该数据。
         */
        Usage: {
            /** Prompt */
            prompt: number;
            /** Completion */
            completion: number;
            /** Total */
            total: number;
            /** Model */
            model: string;
            /** Latency Ms */
            latency_ms: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ask_api_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description NDJSON 事件流，每行一个 JSON 对象。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": unknown;
                };
            };
            /** @description 参数缺失或非法（40001） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 会话不存在（40401） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 依赖不可用：向量库索引缺失（50001）/ 图谱连接或认证失败（50002） */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 云端模型不可用，超时或额度耗尽（50003） */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    ask_graph_api_ask_graph_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description NDJSON 事件流，每行一个 JSON 对象。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": unknown;
                };
            };
            /** @description 参数缺失或非法（40001） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 会话不存在（40401） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 依赖不可用：向量库索引缺失（50001）/ 图谱连接或认证失败（50002） */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 云端模型不可用，超时或额度耗尽（50003） */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_conversations_api_conversations_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Conversation_"];
                };
            };
            /** @description 参数缺失或非法（40001） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 会话不存在（40401） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 依赖不可用：向量库索引缺失（50001）/ 图谱连接或认证失败（50002） */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 云端模型不可用，超时或额度耗尽（50003） */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_conversation_api_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            /** @description 参数缺失或非法（40001） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 会话不存在（40401） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 依赖不可用：向量库索引缺失（50001）/ 图谱连接或认证失败（50002） */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 云端模型不可用，超时或额度耗尽（50003） */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_conversation_api_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 参数缺失或非法（40001） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 会话不存在（40401） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 依赖不可用：向量库索引缺失（50001）/ 图谱连接或认证失败（50002） */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 云端模型不可用，超时或额度耗尽（50003） */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    rename_conversation_api_conversations__conversation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            /** @description 参数缺失或非法（40001） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 会话不存在（40401） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 依赖不可用：向量库索引缺失（50001）/ 图谱连接或认证失败（50002） */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 云端模型不可用，超时或额度耗尽（50003） */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_messages_api_conversations__conversation_id__messages_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Message_"];
                };
            };
            /** @description 参数缺失或非法（40001） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 会话不存在（40401） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 依赖不可用：向量库索引缺失（50001）/ 图谱连接或认证失败（50002） */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 云端模型不可用，超时或额度耗尽（50003） */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
}
